### ISSUE TITLE
Release a new gem version

### ISSUE THREAD

**Issue by lichtamberg** [oleganza/btcruby#21]
The last release is more than 2,5 years ago and but there is development ongoing. Could you release a new version? Mycelium Straight is based on btcruby, so careless people (like me) install a pretty old version of btcruby!!!

**Comment by lichtamberg** [comment]
@oleganza did you already have time to think about a new release? 
Are you looking also for maintainers? I would be happy to contribute...

**Comment by lichtamberg** [comment]
@oleganza I think I will fork this repository and build up on it, if you don't mind and are not looking for a helping hand?

**Comment by oleganza** [comment]
Hi, i'm pretty busy right now with other things, but if you have any PRs, I'll gladly merge them. Thanks!

**Comment by lichtamberg** [comment]
Ok, I would only like to release a new gem version, since f.e. mycelium gear is depending on a pretty old gem version (1.0.6, 2 years old) of btcruby (which also doesnt work correctly).

I don't know how much/what exactly changed, but would you feel ok by just bumping the version to 1.7 or 2 if it contains breaking changes? I can bump the version too and submit a PR, just tell me if/how it's fine for you.

**Comment by oleganza** [comment]
@lichtamberg just pushed a 1.7 update. Should be in rubygems soon.

**Comment by lichtamberg** [comment]
Thanks so much!
